# TYPE  DATABASE       USER                      ADDRESS         METHOD
local   all            postgres                                  peer

hostssl saferwpp_lab   saferwpp_migrator        10.42.0.0/16     scram-sha-256 clientcert=verify-full
hostssl saferwpp_lab   saferwpp_api              10.42.0.0/16     scram-sha-256 clientcert=verify-full
hostssl saferwpp_lab   saferwpp_worker           10.42.0.0/16     scram-sha-256 clientcert=verify-full
hostssl saferwpp_lab   saferwpp_relay            10.42.0.0/16     scram-sha-256 clientcert=verify-full
hostssl saferwpp_lab   saferwpp_report           10.42.0.0/16     scram-sha-256 clientcert=verify-full
hostssl saferwpp_lab   saferwpp_admin            10.42.0.0/16     scram-sha-256 clientcert=verify-full
hostssl saferwpp_lab   saferwpp_monitor          192.168.100.59/32 scram-sha-256 clientcert=verify-full

host    all            all                       0.0.0.0/0       reject
host    all            all                       ::/0            reject
