apiVersion: v1
kind: Namespace
metadata:
  name: saferdock-identity
  labels:
    platform.servidor.local/managed: "true"
    platform.servidor.local/project: saferdock-identity
    platform.servidor.local/saferwpp-dependency: "true"
    pod-security.kubernetes.io/enforce: restricted
    pod-security.kubernetes.io/enforce-version: v1.36
    pod-security.kubernetes.io/audit: restricted
    pod-security.kubernetes.io/audit-version: v1.36
    pod-security.kubernetes.io/warn: restricted
    pod-security.kubernetes.io/warn-version: v1.36
---
apiVersion: v1
kind: Namespace
metadata:
  name: saferdock-platform
  labels:
    platform.servidor.local/managed: "true"
    platform.servidor.local/project: saferdock-platform
    platform.servidor.local/saferwpp-dependency: "true"
    pod-security.kubernetes.io/enforce: restricted
    pod-security.kubernetes.io/enforce-version: v1.36
    pod-security.kubernetes.io/audit: restricted
    pod-security.kubernetes.io/audit-version: v1.36
    pod-security.kubernetes.io/warn: restricted
    pod-security.kubernetes.io/warn-version: v1.36
