apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespaces.yaml
  - project-spaces.yaml
  - blindou-edge-space.yaml
  - service-exposure-policy.yaml
  - production-workload-policy.yaml
